# Generated by Django 3.2.8 on 2021-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skateboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
                ('owner', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
