# Generated by Django 2.1.3 on 2021-10-09 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkateBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('Baker', 'Baker'), ('Birdhouse', 'Birdhouse'), ('Krooked', 'Krooked')], max_length=50)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='value less than the minimum value'), django.core.validators.MaxValueValidator(1.0, message='value more than the maximum value')])),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='value less than the minimum value'), django.core.validators.MaxValueValidator(1.0, message='value more than the maximum value')])),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
