# Generated by Django 2.1.3 on 2021-10-10 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboard',
            name='length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(70.0, message='value less than the minimum value'), django.core.validators.MaxValueValidator(90.0, message='value more than the maximum value')]),
        ),
        migrations.AlterField(
            model_name='skateboard',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2.0, message='value less than the minimum value'), django.core.validators.MaxValueValidator(20.0, message='value more than the maximum value')]),
        ),
    ]
