# Generated by Django 2.1.3 on 2021-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateboard', '0003_auto_20211010_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skateboard',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
